# Generated by Django 4.1.4 on 2024-06-04 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryupload",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
