# Generated by Django 4.1.4 on 2024-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.TextField(blank=True, null=True)),
                ("operation_data", models.JSONField()),
                ("occurrence_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("brief", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text/plain", "Text"),
                            ("text/html", "Html"),
                            ("text/markdown", "Markdown"),
                            ("application/json", "Json"),
                            ("application/xml", "Xml"),
                            ("text/csv", "Csv"),
                            ("application/pdf", "Pdf"),
                            ("application/msword", "Word"),
                            ("application/vnd.ms-excel", "Excel"),
                            ("application/vnd.ms-powerpoint", "Powerpoint"),
                            ("image/jpeg", "Image Jpeg"),
                            ("image/png", "Image Png"),
                            ("image/gif", "Image Gif"),
                            ("audio/mpeg", "Audio Mp3"),
                            ("audio/wav", "Audio Wav"),
                            ("video/mp4", "Video Mp4"),
                            ("video/x-msvideo", "Video Avi"),
                        ],
                        default="text/plain",
                        max_length=64,
                    ),
                ),
                (
                    "visibility",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Public"),
                            (1, "Team"),
                            (2, "Technical Committee"),
                            (3, "Private"),
                        ],
                        default=0,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
