# Generated by Django 4.1.4 on 2024-06-04 15:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("message_bus_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Not Responding"), (1, "Up"), (2, "Down")],
                        default=0,
                    ),
                ),
                ("last_heart_beat", models.DateTimeField()),
                (
                    "queue_status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Running"), (1, "Waiting"), (2, "Stopped")]
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunnerServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True)),
                (
                    "server_status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Running"), (1, "Waiting"), (2, "Stopped")]
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servers",
                        to="runner.runner",
                    ),
                ),
            ],
        ),
    ]
